### PR TITLE
Add linter checks and fix linter warnings

### LINKED ISSUE #51: Add linter to inx-coordinator

### PR DESCRIPTION
**Pull request by muXxer**

### CODE REVIEW

File: pkg/coordinator/quorum.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ type QuorumClientConfig struct {
 	// optional alias of the quorum client.
 	Alias string `json:"alias" koanf:"alias"`
 	// baseURL of the quorum client.
-	BaseURL string `json:"baseURL" koanf:"baseURL"`
+	BaseURL string `json:"baseUrl" koanf:"baseUrl"`
 	// optional username for basic auth.
 	UserName string `json:"userName" koanf:"userName"`
```
Comment (alexsporn) [inline pkg/coordinator/quorum.go]: `Username`

**Review by alexsporn — APPROVED** [review]
